before_script:
  - pwd

Syntax check php7:
  script: find . -name \*.php -exec php -l "{}" \;
  stage: build

Copy paste detection:
  script:
    - wget https://phar.phpunit.de/phpcpd.phar
    - php phpcpd.phar ./src/
  stage: build
  allow_failure: true

PhpUnit php7:
  image: docker.big.hu/test/php:7.2
  script:
    - apt-get update && apt-get install -y php-zip curl
    - php -v
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    - cd tests && php ../vendor/phpunit/phpunit/phpunit
  stage: build

