before_script:
  - pwd

Syntax check php7:
  script: find . -name \*.php -exec php7 -l "{}" \;

Copy paste detection:
  script:
    - wget https://phar.phpunit.de/phpcpd.phar
    - php7 phpcpd.phar ./src/

PhpUnit php7:
  script:
    - pwd
    - php7 -v
    - curl -sS https://getcomposer.org/installer | php
    - php7 composer.phar install
    - cd tests && php7 ../vendor/phpunit/phpunit/phpunit
